name: RUSTSEC audit

on:
  schedule:
    # Run at 00:00 UTC every day
    - cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  audit:
    strategy:
      matrix:
        repository:
        - linkerd2
        - linkerd2-proxy
        - linkerd-await
    runs-on: ubuntu-latest
    name: RUSTSEC audit (${{ matrix.repository }})
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          repository: linkerd/${{ matrix.repository }}
      - uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/audit-check@35b7b53b1e25b55642157ac01b4adceb5b9ebef3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
